# Generated by Django 3.2.5 on 2021-11-11 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('Mobilenumber', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=100)),
                ('foodstyle', models.CharField(max_length=50)),
                ('preference', models.CharField(choices=[('North Indian', 'North Indian'), ('South Indian', 'South Indian'), ('Chinese', 'Chinese')], max_length=50)),
                ('opinion', models.TextField(max_length=100)),
                ('date', models.DateField()),
            ],
        ),
    ]
